export const SET_LOCATION = 'SET_LOCATION';
export const SET_MAP_IMAGES = 'SET_MAP_IMAGES';
export const SET_AREA_IMAGES = 'SET_AREA_IMAGES';
export const SET_FOLLOWING_LOCATIONS = 'SET_FOLLOWING_LOCATIONS';
